name = "100re-web"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./Frontend"
binding = "ASSETS"

[vars]
ADMIN_USERNAME = "100re"
ADMIN_PASSWORD = "100re"
